numpy: numerical python

In [2]:
import numpy as np

In [3]:
#array: an array is a collection of elements
# of same data types

In [4]:
lst = [1,2,3,4,5]
type(lst)

list

In [5]:
arr = np.array(lst)
print(arr)

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr1 = np.array([1,2,3,4,'ankur'])
print(arr1)

['1' '2' '3' '4' 'ankur']


In [8]:
print(arr)
print(arr.dtype)
print(arr.shape)

[1 2 3 4 5]
int64
(5,)


In [9]:
arr_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr_2d)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [10]:
arr_2d.shape

(3, 3)

In [11]:
arr_2d = np.array([[10,20,30],[40,50,60]])
print(arr_2d)

[[10 20 30]
 [40 50 60]]


In [12]:
arr_2d.shape #(rows,columns)

(2, 3)

In [13]:
lst = [1,2,3,4,5]
lst+lst

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [14]:
lst1 = ['a','b','c','d','e']
lst1+lst

['a', 'b', 'c', 'd', 'e', 1, 2, 3, 4, 5]

In [15]:
arr+arr

array([ 2,  4,  6,  8, 10])

In [16]:
arr1 = np.array([1,2,3])
arr+arr1

ValueError: operands could not be broadcast together with shapes (5,) (3,) 